REVOKE ALL ON FUNCTION public.admin_approve_receipt(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_reject_receipt(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.can_download(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.consume_download(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.downloads_today(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.expire_vip_roles() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.increment_download(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.is_active_vip(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_payment_paid() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.validate_resource_access_tier() FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.admin_approve_receipt(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_reject_receipt(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.can_download(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.consume_download(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.downloads_today(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.expire_vip_roles() TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_download(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_active_vip(uuid) TO service_role;